In [241]:
Model includes three functions
    training: Input : X_train, y_train
                Out : theta, mu_jk, sigma_jk
    classify: Input : X,  theta, mu_jk, sigma_jk
                 Out: y_predict
    Acurracy: Input : X_test, y_test,  theta, mu_jk, sigma_jk
                Out : accuracy of model

SyntaxError: invalid syntax (<ipython-input-241-3b5d2897d7b6>, line 1)

In [191]:
import numpy as np
import math

In [197]:
def training(X_train, y_train):
    N,D = X_train.shape
    classes, noElementOfClass = np.unique(y_train, return_counts=True)
    K=classes.size
    theta = np.ones((K,1))
    mu_jk = np.ones((K,D))
    sigma_jk = np.ones((K,D))
    for k in range(0,K):
        theta[k]= noElementOfClass[k] 
        ide = np.where(y_train==classes[k])[-1]
        X=[]
        for i in ide:
             X.append(X_train[i][:])
        X=np.array(X)
        mu_jk[k][:]= np.sum(X,0)/X.shape[0]
        sigma_jk[k][:]= np.square(X[k][:]-mu_jk[k][:])/X.shape[0]
    theta/=N
    return theta, mu_jk, sigma_jk

In [228]:
def classify(theta, mu_jk, sigma_jk, x):
    K,D = mu_jk.shape
    p= np.ones((K,1))
    for k in range(0, K):
        l=np.log(1/np.sqrt(2*np.pi*sigma_jk[k][:]))-(np.square(x[:]-mu_jk[k][:])/(2*sigma_jk[k][:]))
        p[k] = np.log(theta[k])+np.sum(l)
    return np.argmax(p)

In [239]:
def accuracy(theta, mu_jk, sigma_jk,X_test, y_test):
    K, D = sigma_jk.shape
    M, D  = X_test.shape
    y_pre = np.ones((M,1))
    count =0;
    for j in range(0,M):
        y_pre[j] = classify(theta, mu_jk, sigma_jk, X_test[j][:])
        if y_pre[j]==y_test[j]:
            count+=1
    return count/M

In [240]:
X=np.array([[7,2,3,1], [1,2,3,2],[1,3,4,4],[5,10,1,1]])
y=np.array([1,0,1,0])
theta, mu_jk, sigma_jk=training(X, y)
print(theta)
print(mu_jk)
print(sigma_jk)
x=np.array([5,10,1,1])
y=classify(theta, mu_jk, sigma_jk, x)
print(y)
X_test=np.array([[7,2,3,1], [1,2,3,2],[1,3,4,4],[5,10,1,1]])
y_test=np.array([1,0,1,0])
acc= accuracy(theta, mu_jk, sigma_jk,X_test, y_test)
print(acc)

[[0.5]
 [0.5]]
[[3.  6.  2.  1.5]
 [4.  2.5 3.5 2.5]]
[[2.    8.    0.5   0.125]
 [4.5   0.125 0.125 1.125]]
0
0.75
